### ISSUE TITLE
chocpkg install instructions fail with "INSTALL_DIR: unbound variable"

### ISSUE THREAD

**Issue by cvanderw** [chocolate-doom/chocpkg#15]
I followed instructions on the [Chocolate Doom Chocpkg wiki](https://www.chocolate-doom.org/wiki/index.php/Chocpkg) which suggests to do the following:

```
cd chocpkg
./chocpkg install chocolate-doom
```

When I execute that immediately after cloning chocpkg I get the following error:

> /home/christopher/Games/Doom/chocpkg/buildenv.sh: line 44: INSTALL_DIR: unbound variable

Perhaps I'm missing something obvious or some instructions on setting up the INSTALL_DIR variable.

**Comment by cvanderw** [comment]
So I took a look more into this and it appears that buildenv.sh line 44 references INSTALL_DIR but there's no chance to set this variable until basic_setup() in commands.sh is called. I've made a [small change](https://github.com/cvanderw/chocpkg/commit/896a4edd7a79079895bdeffabfa9a1614dc923b9) (to my own fork) to test this out, and this does get things much further, but finally (after doing a lot of building) bails out with the following:

> chocpkg/chocpkg/functions.sh: line 4: ./chocpkg: No such file or directory
> 
> Package chocolate-doom install check is false after install.
> Double check that the check module is defined correctly.

By now the build, build.native, install, install.native, and packages directories were all created.

Again, perhaps I'm just missing something super obvious in setting this up.

**Comment by fragglet** [comment]
I believe this should be fixed now. Thanks!

**Comment by cvanderw** [comment]
Awesome! Thanks for the quick fix. That moves things along when building, however, I'm still seeing the following (as mentioned above) when issuing "./chocpkg install chocolate-doom":

> Package chocolate-doom install check is false after install.
> Double check that the check module is defined correctly.

Should I open a separate issue for this?
